name: manualworkflow

on: 
    workflow_dispatch:
        inputs:
            name:
                description: 'name of the person'
                required: true
                default: 'Santiago'
            
            country:
                description: 'Country'
                required: false
    
jobs:
    greetuser:
        runs-on: ubuntu-latest
        steps:
        - run: |
            echo "Hi ${{github.event.inputs.name}}!"
            echo "Hi ${{github.event.inputs.country}}!"
